// Generated by Dagger (https://dagger.dev).
package com.grand.duke.elliot.restaurantpost.ui.folder;

import com.grand.duke.elliot.restaurantpost.repository.LocalRepository;
import dagger.MembersInjector;
import dagger.internal.InjectedFieldSignature;
import javax.inject.Provider;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class DisplayFolderListDialogFragment_MembersInjector implements MembersInjector<DisplayFolderListDialogFragment> {
  private final Provider<LocalRepository> localRepositoryProvider;

  public DisplayFolderListDialogFragment_MembersInjector(
      Provider<LocalRepository> localRepositoryProvider) {
    this.localRepositoryProvider = localRepositoryProvider;
  }

  public static MembersInjector<DisplayFolderListDialogFragment> create(
      Provider<LocalRepository> localRepositoryProvider) {
    return new DisplayFolderListDialogFragment_MembersInjector(localRepositoryProvider);
  }

  @Override
  public void injectMembers(DisplayFolderListDialogFragment instance) {
    injectLocalRepository(instance, localRepositoryProvider.get());
  }

  @InjectedFieldSignature("com.grand.duke.elliot.restaurantpost.ui.folder.DisplayFolderListDialogFragment.localRepository")
  public static void injectLocalRepository(DisplayFolderListDialogFragment instance,
      LocalRepository localRepository) {
    instance.localRepository = localRepository;
  }
}
